clusterGroup:
  name: hub
  isHubCluster: true
  namespaces:
    - open-cluster-management
    - hello-world
  subscriptions:
    acm:
      name: advanced-cluster-management
      namespace: open-cluster-management
      channel: release-2.10
      #csv: advanced-cluster-management.v2.6.1
  projects:
    - hub
