---
global:
  pattern: multicloud-gitops
  secretStore:
    backend: none
  options:
    useCSV: false
    syncPolicy: Automatic
    installPlanApproval: Manual
    autoApproveManualInstallPlans: true
main:
  clusterGroupName: hub
  multiSourceConfig:
    enabled: true
    clusterGroupChartVersion: "0.9.*"
